<?php

namespace SG\AdminBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * DeudaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeudaRepository extends EntityRepository {

    public function findVencimientosDelMes() {
        $hoy = new \DateTime();
        $desde = new \DateTime('first day of this month');
        $hasta = new \DateTime('last day of this month');

        $query = $this->_em->createQueryBuilder();
        $query->select('d')
                ->from('SG\AdminBundle\Entity\Deuda', 'd')
                ->where("d.fechaVto between '" . $desde->format('Y-m-d') . "' and '" . $hasta->format('Y-m-d') . "'")
                ->orderBy('d.fechaVto');
        return $query->getQuery()->getResult();
    }

}