seguridad_perfil:
    pattern:  /
    defaults: { _controller: "ConfigBundle:Perfil:index" }

seguridad_perfil_new:
    pattern:  /new
    defaults: { _controller: "ConfigBundle:Perfil:new" }

seguridad_perfil_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ConfigBundle:Perfil:edit" }

seguridad_perfil_create:
    pattern:  /create
    defaults: { _controller: "ConfigBundle:Perfil:create" }
    requirements: { _method: post }

seguridad_perfil_update:
    pattern:  /{id}/update
    defaults: { _controller: "ConfigBundle:Perfil:update" }
    requirements: { _method: post|put }

seguridad_perfil_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ConfigBundle:Perfil:delete" }
    requirements: { _method: post|delete }
